spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/tenants
    platform: h2
    username: admin
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 900000